name: CI

on:
  push:
    branches: [master, preprod]
  pull_request:
    branches: [master, preprod]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.46.1
      with:
        ruby-version: 2.7.0

    - name: Install and run Yarn
      uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: install

    - name: Install dependencies
      run: |
        sudo apt install -yqq libpq-dev
        gem install bundler

    - name: Install Gems with Bundler
      run: bundle install --jobs 4

    - name: Prepare Database
      run: |
        bundler exec rails db:create RAILS_ENV=test
        bundler exec rails db:migrate RAILS_ENV=test

    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:@localhost:5432/devops_stephanyan_test
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      run: bundle exec rspec
