name: Deploy preprod to Heroku

on:
  push:
    branches:
      - preprod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_PREPROD_APP_NAME: ${{ secrets.HEROKU_PREPROD_APP_NAME }}
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PREPROD_APP_NAME.git origin/master:master
