name: Deploy preprod to Heroku

on:
  push:
    branches:
      - preprod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v2
    # - name: Deploy to Heroku
    #   env:
    #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    #     HEROKU_PREPROD_APP_NAME: ${{ secrets.HEROKU_PREPROD_APP_NAME }}
    #   if: github.ref == 'refs/heads/preprod' && job.status == 'success'
    #   run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PREPROD_APP_NAME.git origin/master:preprod
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_PREPROD_APP_NAME }} #Must be unique in Heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
